import { Metadata } from 'next';
import { Inter } from 'next/font/google';
import AppThemeProvider from './_components/DefaultThemeProvider';
import Navbar from './_components/Navbar';
import './globals.scss';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <AppThemeProvider>
          <Navbar />
          <main>{children}</main>
        </AppThemeProvider>
      </body>
    </html>
  );
}
